### ISSUE TITLE
[About > Contact]

### ISSUE THREAD

**Issue by liamrosen** [c19-rnd-dashboard/covid-trials-dashboard#118]
This should be super simple.

![image](https://user-images.githubusercontent.com/718461/97033629-81710c00-1518-11eb-9ccc-5e86f05a490f.png)

**Comment by j10sanders** [comment]
@liamrosen should I give your email for the media section?

**Comment by liamrosen** [comment]
I don't actually think we need a media section for now. We can separate it
out once we start getting too many emails into info@
