### ISSUE TITLE
Analytics tracking when someone clicks "How to Volunteer" on a pin

### ISSUE THREAD

**Issue by liamrosen** [c19-rnd-dashboard/covid-trials-dashboard#143]
This will be helpful to track site visits vs. "conversions"

**Comment by j10sanders** [comment]
I'll copy https://medium.com/@malith.dev/track-users-in-your-react-app-with-google-analytics-6364ebfcbae8

Can you or Mats share GA login for me so I can test?

**Comment by j10sanders** [comment]
Looks like Nestor did this 4 months ago

`ReactGA.event({
      category: 'volunteer',
      action: 'How to volunteer clicked',
      label: 'Popup button, how to volunteer',
    })`

![Screen Shot 2020-11-05 at 8 28 34 PM](https://user-images.githubusercontent.com/11084414/98315150-8ff20580-1fa5-11eb-8d0d-5629d322c962.png)
