### ISSUE TITLE
[Map] Prefill mailto link with subject and body of message to the trials email

### ISSUE THREAD

**Issue by liamrosen** [c19-rnd-dashboard/covid-trials-dashboard#148]
![image](https://user-images.githubusercontent.com/718461/97933388-75aaf400-1d27-11eb-913d-5b9ebe8f665a.png)

**Comment by j10sanders** [comment]
Hey, can you and/or Mats come up with what content and title you would like in the email?

**Comment by j10sanders** [comment]
pinging @liamrosen

**Comment by liamrosen** [comment]
Mats is going to do it since he knows best what works.

**Comment by mats-o** [comment]
Subject: I am interested in volunteering for your clinical trial

Body: 
Hello, 

I am interested in participating in your clinical trial for a COVID-19 vaccine.  I am a healthy subject who has not had COVID-19 and is not experiencing COVID-19 symptoms.  I am located in <ENTER CITY> and can be reached at this email.  Please let me known the next steps for potentially being screened and enrolled in this important study. 

<SIGNATURE>

**Comment by liamrosen** [comment]
Love it. What do we think about a "Sent by http://www.coviddash.org" at the bottom. Too much? Could be good marketing for us to the pharma companies, at least initially

**Comment by mats-o** [comment]
I like it a lot! Let's do it. Or maybe we could build it into the body of the email.  "I found your study on www.coviddash.org and I am interested in participating..." up to you guys.

**Comment by liamrosen** [comment]
Body of the email is perfect.
