### ISSUE TITLE
Change font of website to match logo

### ISSUE THREAD

**Issue by liamrosen** [c19-rnd-dashboard/covid-trials-dashboard#150]
https://helpx.adobe.com/fonts/user-guide.html/fonts/using/add-fonts-website.ug.html

**Comment by j10sanders** [comment]
Which font?

**Comment by j10sanders** [comment]
Pragmatica and pragmatica slab serif

**Comment by j10sanders** [comment]
the header isn't picking it up... it's all going pragmatica. Will check with Sunny if this is worth more time.
