### ISSUE TITLE
Map still slow on desktop and mobile

### ISSUE THREAD

**Issue by liamrosen** [c19-rnd-dashboard/covid-trials-dashboard#186]

**Comment by j10sanders** [comment]
Ok I'm not going to close this out until @Nestyko confirms this is faster, but I've been able to cut out all the re-renders of the Pins by using `useMemo` in https://github.com/c19-rnd-dashboard/covid-trials-dashboard/pull/189

**Comment by j10sanders** [comment]
actually I'm quite confident this worked but will wait to see what Nestor says before closing this out!

**Comment by j10sanders** [comment]
It's not perfectly speedy but it's an improvement.  I'll close this out and if we decide to prioritize making it even faster we can do that in a new ticket.
