### ISSUE TITLE
Add missing FAQ question (that Mats just added)

### ISSUE THREAD

**Issue by liamrosen** [c19-rnd-dashboard/covid-trials-dashboard#188]

**Comment by j10sanders** [comment]
@mats-o sorry this took so long!  done now.

**Comment by mats-o** [comment]
Hi @j10sanders , I'm not seeing Q&A on the website, is it a cache problem on my side?  The Q&A should be the "Why Volunteer if we already have a vaccine" one here: https://docs.google.com/document/d/1Mw-CfAzezFh6sFKRKlERU2HxX_e5Lu5bXSUcjVD5gso/edit?usp=sharing
