### ISSUE TITLE
Mapbox browsing issue on mobile devices 

### ISSUE THREAD

**Issue by hurshd0** [c19-rnd-dashboard/covid-trials-dashboard#89]
When trying to navigate the map and clicking on pins popup is too big and can't be re-sized or closed by tapping out.

https://drive.google.com/file/d/18yQv7kC3dNtKD9Vw7lRlBuLNDIGtrUiR/view?usp=sharing

Give the popup a width depending on mobile or desktop so it looks nice. Also there is a function on mapbox that can be used to center the Pin on Click, that might be helpful as well.

From Mats:
-on mobile-
"Remove all but first sponsor name, remove product, remove Trial Registry Link.  If need be you can remove Phase as well."

Resources if needed: 
* https://material-ui.com/components/use-media-query/#using-material-uis-breakpoint-helpers
* https://material-ui.com/customization/breakpoints/#css-media-queries

**Comment by j10sanders** [comment]
@hurshd0 - let me know what you think of it now.  I made some changes in https://github.com/c19-rnd-dashboard/c19-rnd-dashboard-ui/pull/97
